name: Alerta Milhas

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  rodar-alerta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          WHATSAPP_DESTINO: ${{ secrets.WHATSAPP_DESTINO }}
        run: python main.py
